name: CI to Docker hub 

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "justfile"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "justfile"
  
jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and push
          if: "!contains(github.event.head_commit.message, '***NO_BUILD***')"
          uses: docker/build-push-action@v3
          with:
            context: .
            push: true
            file: ./Dockerfile.ubuntu2204
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/shell:latest
            cache-to: type=gha,mode=max

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}

        - name: Update repo description
          uses: peter-evans/dockerhub-description@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            repository: ${{ secrets.DOCKER_HUB_USERNAME }}/shell
